# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    # 1. Type Check - Strict mode
    type-check:
      run: npm run type-check
      glob: '*.{ts,tsx}'

    # 2. Lint & Fix - Prettier + ESLint
    lint:
      run: npm run lint -- --fix
      glob: '*.{js,ts,jsx,tsx}'

    # 3. Prettier check (just in case)
    format:
      run: npm run format
      glob: '*.{js,ts,jsx,tsx,css,json,md}'
